"""
Ключевые слова для поиска ссылок на страницы контактов.

Используются при парсинге главной страницы сайта работодателя
для обнаружения ссылок на страницы с контактной информацией.
"""

CONTACT_KEYWORDS = [
    # Контакты (основные)
    "контакты",
    "контакт",
    "contact",
    "contacts",
    "contact us",
    "связаться",
    "связаться с нами",
    "свяжитесь с нами",
    "обратная связь",
    "feedback",
    "get in touch",
    "написать нам",
    "напишите нам",
    "write us",
    "send message",
    "send us a message",
    # Телефоны
    "телефон",
    "телефоны",
    "phone",
    "phones",
    "telephone",
    "tel",
    "call us",
    "позвонить",
    "позвоните",
    "звонок",
    "callback",
    "перезвонить",
    "заказать звонок",
    # Email
    "email",
    "e-mail",
    "почта",
    "электронная почта",
    "mail",
    "mail us",
    "email us",
    # Адреса и офисы
    "адрес",
    "адреса",
    "address",
    "addresses",
    "офис",
    "офисы",
    "office",
    "offices",
    "расположение",
    "location",
    "locations",
    "как добраться",
    "как нас найти",
    "где мы",
    # О компании
    "о компании",
    "о нас",
    "about",
    "about us",
    "about company",
    "our company",
    "наша компания",
    "информация о компании",
    "company info",
    "company information",
    # Реквизиты
    "реквизиты",
    "юридический адрес",
    "legal",
    "legal info",
    "requisites",
    # HR и вакансии
    "вакансии",
    "вакансия",
    "vacancies",
    "vacancy",
    "карьера",
    "careers",
    "career",
    "работа",
    "jobs",
    "job",
    "hiring",
    "we are hiring",
    "join us",
    "join our team",
    "hr",
    "кадры",
    "персонал",
    "personnel",
    "recruiting",
    "recruitment",
    "talent",
    "people",
    # Руководство
    "руководство",
    "директор",
    "director",
    "ceo",
    "management",
    "administration",
    "администрация",
    "основатель",
    "founder",
    "founders",
    "owner",
    "owners",
    "executive",
    "executives",
    "leadership",
    "board",
    "directors",
    # Поддержка
    "поддержка",
    "support",
    "help",
    "помощь",
    "служба поддержки",
    "customer service",
    "customer support",
    "help desk",
    "сервис",
    "service",
    # Социальные сети
    "социальные сети",
    "соцсети",
    "social media",
    "socials",
    "follow us",
    "подписаться",
    "telegram",
    "whatsapp",
    "viber",
    "skype",
    "linkedin",
    "facebook",
    "instagram",
    "vk",
    "vkontakte",
    # Партнёрам
    "партнёрам",
    "партнерам",
    "partners",
    "partnership",
    "сотрудничество",
    "cooperation",
    "for partners",
    # Для клиентов
    "клиентам",
    "for clients",
    "for customers",
    "клиенты",
    "clients",
    "customers",
    # Пресса и СМИ
    "пресс",
    "press",
    "media",
    "сми",
    "journalist",
    "журналист",
    # Инвесторам
    "инвесторам",
    "investors",
    "for investors",
    "investor relations",
    "акционерам",
    "shareholders",
    # Поставщикам
    "поставщикам",
    "suppliers",
    "vendors",
    "for suppliers",
    "закупки",
    "procurement",
    "tenders",
    "тендеры",
    # Документы
    "документы",
    "documents",
    "политика",
    "policy",
    "privacy",
    "terms",
    "условия",
    # Команда
    "команда",
    "team",
    "our team",
    "наша команда",
    "staff",
    "сотрудники",
    "employees",
    "наши люди",
    "our people",
    # Форма обратной связи
    "форма",
    "form",
    "contact form",
    "форма связи",
    "форма заявки",
    "заявка",
    "inquiry",
    "request",
    "запрос",
    "задать вопрос",
    "ask a question",
    # Отделы
    "отдел",
    "department",
    "отдел продаж",
    "sales",
    "продажи",
    "отдел кадров",
    "отдел маркетинга",
    "marketing",
    "маркетинг",
    "pr",
    "public relations",
    # Дополнительное
    "connect",
    "reach us",
    "reach out",
    "lets talk",
    "let's talk",
    "talk to us",
    "chat",
    "message us",
    "drop us a line",
    "наши контакты",
    "наши контактные данные",
    "контактные данные",
    "контактная информация",
    "contact info",
    "contact information",
]


__all__ = ("CONTACT_KEYWORDS",)
